# gitlab pipeline config

image: node:12.0.0

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - yarn
    - yarn build
  artifacts:
    expire_in: 1 day
    paths:
      - build

DEPLOY:
  stage: deploy
  script:
    - yarn deploy
  only:
    - master
